### ISSUE TITLE
Page break behaviour

### ISSUE THREAD

**Issue by flokl** [python-openxml/python-docx#1117]
Hi, 
I researched page breaks a bit, so I understand soft breaks in Word are hard, because they are dependent on the amount of content and Word only renders them after the document is opened. 
I have a document with manual inserted  hard page breaks (with ctrl+enter) and if I replace with it self `paragraphs.runs.text = paragraphs.runs.text` the following happens:
Before:
`  <w:br w:type="page"/>
</w:r>`
After replace:
`  <w:br/>
</w:r>`
Is this intended behaviour? Are hard page breaks also that hard? Do I have to manually but back in the page breaks at xml level?

I hope this is the right place to ask.

**Comment by icegreentea** [comment]
The change happens because when you call `run.text` the library serializes all the content in the run into a python string - for example, turning `<w:t>` into `\t` and all `<w:br>` elements (regardless of type) into `\n`. Then in the `run.text` setter, the python string is deserialized - the `\n` elements are turned back into `<w:br>` (without the type). That's why break behavior changes.

I think this is somewhat intended behavior. This behavior makes sense for letting the library interact with other code/library more easily.

One work around for now is to implement your own text cloning function for runs. I sketched out one below:

```
def clone_run_text(source_run_element, destination_run_element):
	from docx.oxml.ns import qn
	from copy import deepcopy
	
	clone_tags = (
		qn("w:t"), qn("w:tab"), qn("w:br"), qn("w:cr"),
	)
	destination_run_element.clear_content()
	for child in source_run_element:
		if child.tag in clone_tags:
			destination_run_element.append(deepcopy(child))
	
# usage
r1 = doc.paragraphs[0].runs[0]._r
r2 = doc.paragraphs[1].runs[1]._r
clone_run_text(r2, r1)
```

This method will:
* preserve any existing run formatting in `destination_run_element`
* copy over all the text, br, tab and cr elements from source to destination
* nuke any drawings in `destination_run_element`

**Comment by flokl** [comment]
I did not think about this use case, thank you for the excellent explanation and the workaround code, much appreciated.
