### ISSUE TITLE
ImportError from docx import Document

### ISSUE THREAD

**Issue by Delltinha** [python-openxml/python-docx#1155]
I'm having this error and can't find anywhere how can I solve.
I already tried to reinstall all modules and nothing change, can someone help me with this?

Exception has occurred: ImportError
cannot import name 'Document' from partially initialized module 'docx' (most likely due to a circular import) (c:\Users\Dellta\Desktop\Python\Contrato Automatico\docx.py)
  File "C:\Users\Dellta\Desktop\Python\Contrato Automatico\docx.py", line 1, in <module>
    from docx import Document
  File "C:\Users\Dellta\Desktop\Python\Contrato Automatico\docx.py", line 1, in <module>
    from docx import Document

Code:
`from docx import Document

document = Document()
document.add_heading("Title", 3)
document.add_paragraph("This is my line")

document.save("NewDocx.docx")`

**Comment by jbasko** [comment]
It is because you have called your Python module `docx` — the path to your file is `c:\Users\Dellta\Desktop\Python\Contrato Automatico\docx.py`. This means that when you say `import docx`, you are not attempting to import from `python-docx` package `docx`, but from your module itself. Hence Python says it's a circular import. Rename your file to something else.

**Comment by paguielng** [comment]
The error you're experiencing is happening because your Python script is named `docx.py`, which causes a conflict with the `docx` library you're trying to import. When you use `import docx`, Python attempts to import from your own script instead of the `python-docx` package, leading to the circular import error.

To resolve this:

1. Rename your script to something other than `docx.py` (e.g., `contract_auto.py`).
2. If there are any `.pyc` files or a `__pycache__` folder, delete them to avoid further issues with cached imports.
3. After renaming the file, try running your script again.

This should fix the issue and allow you to use the `python-docx` package correctly. Let me know if you need further assistance!
