### ISSUE TITLE
'lxml.etree._Element' object has no attribute 'Relationship_lst'

### ISSUE THREAD

**Issue by tcosmo** [python-openxml/python-docx#1180]
My application uses `python-docx` in production and we often get the following error:

`'lxml.etree._Element' object has no attribute 'Relationship_lst'`

Which comes from this piece of code `docx/opc/pkgreader.py` line 286 (v0.8.11):

```python
@staticmethod
def load_from_xml(baseURI, rels_item_xml):
    """
    Return |_SerializedRelationships| instance loaded with the
    relationships contained in *rels_item_xml*. Returns an empty
    collection if *rels_item_xml* is |None|.
    """
    srels = _SerializedRelationships()
    if rels_item_xml is not None:
        rels_elm = parse_xml(rels_item_xml)
        for rel_elm in rels_elm.Relationship_lst:
            srels._srels.append(_SerializedRelationship(baseURI, rel_elm))
    return srels
```

Unfortunately, I am not able to reproduce this bug deterministically, it is quite mysterious.

The application is deployed on Google Cloud Run which somehow seems to maybe have an influence here as I have been absolutely unable to reproduce the bug locally.

**Comment by scanny** [comment]
This looks like a problem with the parsing. The `rels_item_xml` is one of the `.rels` "files" from the package, like `word/_rels/document.xml.rels`. This should automatically parse into a `docx.opc.oxml.CT_Relationships` object by `lxml`'s custom-element-class behavior. The "`lxml.etree._Element object ...` prefix indicates that's not happening (`etree._Element` is the base class for the custom element classes and the default when the tag doesn't match a more specific one).

My bet is that the XML namespace of the relationships part (and maybe more broadly, just first discovered here) is not the expected one, which is: `pr: http://schemas.openxmlformats.org/package/2006/relationships`. If you inspect the relationships object in question, probably the one named `_rels/.rels` if you unzip the .docx file, you're looking for this on the root element:
```
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
```
If the `xmlns` (XML namespace) value is not exactly this one, that would explain the problem. Could be a LibreOffice difference or possibly a file-format conversion problem, depending on what you're doing.

I'm going to close the issue because it took me so long to get to it, but this is an interesting problem and I'd love to know what you discovered. Could bear on future work. Feel free to reopen if there's more to say, and thanks for reporting it :)
