### ISSUE TITLE
Feature: Find / replace text and generally *modify* docx files

### ISSUE THREAD

**Issue by MarcusJones** [python-openxml/python-docx#12]
I'm doing a lot of work with existing docx (creating many docx from a template). I hacked this together but there are better ways I think, any plans to natively increase support in modifying docx? XPATH? This is my main use case. 

```
def replace(document, search, replace):
    """Walk the tree down to w:t xml and update text node"""
    searchre = re.compile(search)
    count = 0

    # Loop over all paras in doc
    for para in document.paragraphs:
        # Loop over all runs in para
        for run in para.runs:
            if len(run._r.t_lst) > 1:
                raise
            if len(run._r.t_lst) == 1:
                element_wt = run._r.t_lst[0]
                this_text = element_wt.text
                if searchre.search(this_text):
                    newtext = re.sub(search, replace, this_text)
                    count += 1
                    element_wt.text = newtext
            else:
                continue

    logging.debug("Replaced {} with {} {} times".format(search, replace, count))
```

**Comment by aprasanth90** [comment]
@scanny 
Hello Scanny,

I am currently trying replicated exactly what Pradeep tried to do. 

---
My name Is Mr.X,
I am Working at Company x.

I want to replace multiple place holders on the word document.

My name Is $name,
I am Working at $company
----
I have template with pre-filled variable that I would like to replace with the value I provide in my script.

I have worked with Django and I was reading on your suggestion on curated template. 

Can you please expand on it.

Thank you for time

**Comment by scanny** [comment]
@aprasanth90, @holli-holzer The basic idea is this:

* get a template from somewhere
* render it into final XML using Django Templating or Mako or whatever
* inject that XML into the ._blob field of the target part, likely the DocumentPart object.

The template part can come from anywhere, but the last time I did it I stored it directly in the starting document as its document.xml part. I might like to do that differently in future because it limits what templating features you can use, is not well suited to version control if kept in its .docx (Zip) format, and is prone to corruption if edited in Word.

The template itself is based on the XML from one of the document 'parts'. The main document part is 'word/document.xml' when you unzip the .docx file. The opc-diag package is a handy way to get that neatly unzipped and pretty-printed ready for templating.

One aspect of this overall approach is you end up having to understand the WordprocessingML well enough to accomplish what you want. Usually that's easy enough by creating a document with Word that looks like what you want and then just finding the bits you want to change and replacing them with templating placeholders. But it does generally place it outside what's possible for end-users to do for themselves.

The rendering part I expect you understand well enough.

Once you have the final XML, you inject it into the DocumentPart something like this. Note the XML must be bytes before you inject it, not unicode. So depending on what you get back from your templating engine you may have to encode it as 'utf-8', e.g. `xml_bytes = xml_unicode.encode('utf-8')`:

```python
document = Document()
document_part = document._document_part
document_part._blob = xml_bytes_rendered_from_template
```

If you store the template in the starting document, you access it something like this:

```python
document = Document('my-template.docx')
document_part = document._document_part
template = document_part._blob
```

Note that python-docx supports opening a document from an expanded .docx zip archive. If your template .docx was expanded into the directory 'my-template', loading it would look like this:

```python
document = Document('my-template')
document_part = document._document_part
template = document_part._blob
```

I like that approach better than using a .docx file because you can keep the entire expanded template directory tree under version control with the rest of your source. This is what I referred to above as a "curated" template.

That should give you a start :)

**Comment by holli-holzer** [comment]
I have added a templating proof of concept with support for django and jinja engines.

Here's a diff: http://hastebin.com/cakuxusaci.diff

Usage is as easy as

```python
###################################################

import os, sys

sys.path.append("..")

from docx.api import Document

c = {
    'scalar': 'The FSM', 
    'liste': [
        {'name':'foo', 'data':[1,2,3], "baz":"abc", "date":"112"},
        {'name':'bar', 'data':['three', 'four', 'five'], "baz":"def", "date":"1132"},        
    ]
}

#
# loop over all test files and process them
#
for p in ["test_template_edge_case_1.docx", "test_template_edge_case_2.docx", "test_template_features.docx"]:
    for e in ["django", "jinja"]:
        i = os.path.join("test_files", e, "in", p)
        o = os.path.join("test_files", e, "out", p)
        d = Document(i)
        d.save(o, context=c, engine=e)

###################################################
```

**Comment by holli-holzer** [comment]
Oh, I gues I should mention, that this solution supports templates to be written in word (or ooffice or whatever) itself as well as handcrafted templates. I have created a new branch. If anybody is interested in the code or the example template files let me know.

**Comment by Epithumia** [comment]
I've been trying to replace the _part (I assume that's what _document_part is supposed to be) of my document, but upon saving, it just saves the original version. render(...) calls jinja2 on a jinja2 template which is the original _blob which I saved to a file then turned into a jinja2 template.

```python
from docx import Document
doc = Document('modele.docx')
xml_unicode = render('/templates/my_doc.jinja2', {'data': some_data})
doc._part._blob = xml_unicode.encode('utf-8')
doc.write('output.docx')
```
On the other hand, using zipfile to flat out replace the document.xml and then repacking the file works.

**Comment by scanny** [comment]
DocumentPart._blob is not used to write the document part. DocumentPart._element is serialized to get a new blob based on changes made to the XML.

So you'll need to replace DocumentPart._element, something like this:

```python
from docx.oxml import parse_xml
doc._part._element = parse_xml(xml_unicode.encode('utf-8'))
doc.save('output.docx')
```

You're on your own for any external relationships that might get put out of sync, such as for hyperlinks or images; but if you can avoid or accommodate that this should work fine :)

**Comment by Epithumia** [comment]
Right, this works now. Thanks.

**Comment by backbohne** [comment]
I wrote a docx XSL tranformation module based on holli-holzer basic ideas: https://github.com/backbohne/docx-xslt

**Comment by karelv** [comment]
@holli-holzer, It sounds like a great feature you added.
Do you have any plans to make a pull request?

**Comment by holli-holzer** [comment]
@karelv no. i have uploaded the fork and if steve wants to he can easily pull it in.

**Comment by ullrichc** [comment]
@scanny Any plans to pull it in?

**Comment by scanny** [comment]
No; no plans to pull this fork in. There are no tests and minimally the structure would need to be adjusted to be consistent with the rest of the library. I expect there are a number of other work items that would be involved as well.

I believe @holli-holzer intended it as a proof-of-concept, which it does nicely as far as I can tell. But the heavy lifting of incorporating it into the broader code base remains to be done and I have no current plans to undertake it.

**Comment by mrufsvold** [comment]
I have a question related to this conversation. 

I need to edit the text of the footer of an existing document that relies on a custom template. However, `doc.sections[0].footer.paragraphs` returns an empty list. 

When I unzipped the underlying xml, I find that the text that is currently in the document's footer, is stored in a file called `footer2.xml`. I assume that it is broken out like this because of the way the original document is constructed by the custom template which is why I'm posting in this topic. 

After reading all of your solutions above, @scanny, I think I'm having a mental block because I don't know how the various docx and xml functions you're using map on to reading the actual xml files as they exist. So if I want to access an element in a specific file and change it's contents, I don't know how to find it. But I think that mental block is mostly because I'm thinking about the problem in the wrong way. 

Any advice you can give would be much appreciated!

**Comment by scanny** [comment]
The "separate files" you mention are known as "parts" (like "document parts") in the Open Packaging Convention (OPC). Things can be broken up for various reasons, but yes, headers and footers are separate parts. All document parts are loaded at the `Document(...)` call time. A part is "connected" to another part by a _relationship_ (sometimes `rel` or `rels` in the code). The code for part base classes is in `docx.opc.part`. The classes for custom parts (most of the ones you see) are in `docx.part`.

The user (programmer) doesn't generally interact directly with a part object. Instead the main element of the XML in the part is used to instantiate an _element-proxy_ object (like `Document`, `Header`, etc.) and the API is the methods on that object.

When you call, for example, `section.header`, that relationship is traversed, the header part (`HeaderPart` object) is accessed, and the `Header` object you get back is a proxy for the `w:hdr` element at the root of the XML stored in the header part.

So you need to get to the part by traversing whatever relationships are involved and then access the part contents from there.

What part and what contents were you after in particular?

**Comment by mrufsvold** [comment]
I'd like to update the date in the footer of the document when my program runs:

<img width="284" alt="image" src="https://user-images.githubusercontent.com/86363075/144650344-36b14fb2-5835-446d-a35d-fd20f588070c.png">

There is a date in the header that I'm able to access and edit from `Document('mydoc.docx').sections[0].header.paragraph[0].runs`. For some reason, I can't access the footer using the same method (replacing `header` with `footer` of course). 

If it is helpful, I searched the XML and found the text I'd like to change in the part called footer2.xml. Screensheet for context --
<img width="468" alt="image" src="https://user-images.githubusercontent.com/86363075/144651148-6642d019-462f-43f0-90b1-0ac86f7c126d.png">

I hope that is the context you need.

**Comment by scanny** [comment]
check in `.first_page_footer` and `.even_page_footer` as well to see if you find it there. `.footer` returns the default footer (which also serves as the odd-page footer when `.even_page_footer` is defined).

**Comment by mrufsvold** [comment]
Both of these attributes exist and .paragraphs return a list with one paragraph. The paragraph.text attribute returns an empty list for both. Only difference is that .footer.paragraphs returns an empty list with no paragraph object.

**Comment by scanny** [comment]
What about `.tables`. Sometimes folks like the idea of placing footer items in a table as an easy way to keep the page number distinct from whatever is in the text part.

**Comment by mrufsvold** [comment]
No dice! `.tables` is empty. I think I may just have the analysts using this document manually update the footer when they go in 🤷

**Comment by scanny** [comment]
If you want to pursue, then look in the .rels file/part for the document and see which relationship points to `footer2.xml`. Then find the `rId` of that relationship and find it in the XML for the document. Is it possible there is more than one section in the document and you're inspecting the wrong one?
