### ISSUE TITLE
Word Documents SaveAs PDF Documents

### ISSUE THREAD

**Issue by vonyang** [python-openxml/python-docx#1243]
I have a .docx file, and I want it to convert it into a PDF file, is there any method to do it using python-docx, I know that with pywin32 is easy to do it. Also, I want to save it as a stream and not in a file, using 'io' (BytesIO) library.

**Comment by scanny** [comment]
No. And there is unlikely ever to be such a feature in `python-docx` because it is essentially a _document format conversion_ operation, which is a distinct "space" so to speak.

You can look into pandoc for this or one of the other options mentioned in this StackExchange question: https://unix.stackexchange.com/questions/105584/convert-a-docx-to-a-pdf-with-pandoc

From a quick read of that post it sounds like there are some passable solutions, none of which I'm sure are as clean as what Word itself would produce.

**Comment by vonyang** [comment]
The thing it's that I'm working with automation proccess in python so if you know a way to convert a word document into pdf.
