### ISSUE TITLE
How to modify table/paragraph/footnote text without destroying the formatting

### ISSUE THREAD

**Issue by eZWALT** [python-openxml/python-docx#1251]
Hello guys, first of all thank you for this project, it enables me for a personal project of word/pptx translation. I would want to know how i could modify all the text without modifying the styling, font,colors ... I was just testing yesterday this loops to traverse the tables & paragraphs for example.

        docx_doc = docx.Document(source_file) 
        for paragraph in docx_doc.paragraphs:
            if paragraph.text: 
                paragraph.text = "dummy text"

        for table in docx_doc.tables:
            for row in table.rows:
                for cell in row.cells:
                    if cell.text:
                            cell.text = "304"

        output = BytesIO()
        docx_doc.save(output)
        output.seek(0)

This works but it doesn't preserve the original font nor color and i imagine that a bunch of other things that i'm not even considering. I've been reading the documentation time to time for over a time and i yet don't understand this project well. 

Thank you guys for your time & efforts!

**Comment by scanny** [comment]
This is a thorny problem because the actual structure of the text tends to become very fragmented.

If you take a real-live paragraph from a Word document that has been edited several times and `print(paragraph.xml)` you'll see that runs can be broken at several places, even though the formatting of adjacent runs is the same in many cases. This is because Word applies a _revision-save id_ (RSID) to all text entered in an editing session (period between saves).

So the text you want to replace is not all in one handy location. You would need to code at the XML level and either join together runs or distribute your changes across multiple runs.

The conversation on this issue might be a help: https://github.com/python-openxml/python-docx/issues/980
