### ISSUE TITLE
Missing sdist for 1.0.0 on PyPI

### ISSUE THREAD

**Issue by musicinmybrain** [python-openxml/python-docx#1257]
The [1.0.0 release on PyPI](https://pypi.org/project/python-docx/1.0.0/#files) lacks a sdist (`python-docx-1.0.0.tar.gz`).

As the maintainer of the Fedora Linux and EPEL [`python-docx` package](https://src.fedoraproject.org/rpms/python-docx), I use the PyPI sdists as the sources for the distribution packages.

I cannot use the GitHub archive, e.g. https://github.com/python-openxml/python-docx/archive/refs/tags/v1.0.0.tar.gz, directly, because the [`ref/` directory](https://github.com/python-openxml/python-docx/tree/v1.0.0/ref) contains documents that cannot be freely redistributed. (I suspect those should not be tracked here at all, given the terms on ISO/IEC standards.) Since the PyPI sdist omits `ref/` but has everything else I need, it sidesteps the problem.

I could package 1.0.0 by downloading a GitHub archive, extracting it, removing `ref/`, re-compressing it, and using that as the source archive for packaging—and there are other packages for which I have to do that sort of thing—but having the sdist on PyPI would be much simpler.

Thanks!

**Comment by scanny** [comment]
Hi @musicinmybrain, that was not intentional, thanks for bringing that to my attention. I believe it is remedied now and we certainly plan to include the source distribution in PyPI releases.

Thank you for your work to maintain the Fedora and EPEL versions of the package. Feel free to reach out any time if there's something you need from us :)

**Comment by musicinmybrain** [comment]
Awesome, thanks!
