### ISSUE TITLE
Add Page Break Issue

### ISSUE THREAD

**Issue by msloat450** [python-openxml/python-docx#1260]
I am new to python-docx, so this might not be an issue but just that I don't know what I am doing.  I found an example that was similar to this, but I couldn't figure it out.  I was hoping someone could help.

I have been experimenting with creating a docx file that can be appended to by another word document, and so on.  The process would work like this.  Initially, the target document 'target.docx', when the program first ran, would just be turned to final.docx.  Simple... The next time a document was added, it would combine final.docx with the target 'target.docx.'  I have been using add_page_break() to separate the pages.  I don't have a problem with just creating the page initially, or when I combine the files for the first time.  But when I combine final.docx that has already been combined once, the page break will go after the first page of the already combined document.

Probably easier to explain this way.

1) First page added.  There is no page break added so that the page doesn't overlap another.

Page 1

2)  The second page is added to the first.  The page break is done after Page 1.

Page 1

Page Break

Page 2

3) Page 1 / Page Break / Page 2 are now one page called final.docx.  It is added again to another target doc. Somehow the page break is added to the middle of the final.docx.  Which at this point I am considering to be just page 1.  (Or Page 1 / page break / Page 2)

Page 1

Page Break

Page Break

Page 2

Page 3.

The original program I had trouble with, so I decided to knock it down into parts to see what was going on.  Keep in mind that demo is like the final.docx and demo1 is similar to the target document.  When creating the original file, all I do it use docs = Document('pre.docx') and then save it as testReport1.docx.

demo = 'testReport1.docx'

demo1 = 'pre.docx'
doc = []
doc.append(Document(demo))

doc.append(Document(demo1))

doc[0].add_page_break()
doc[0].add_paragraph('')

for ep in doc[1].element.body:
    doc[0].element.body.append(ep)

doc[0].save('testReport1.docx')

**Comment by scanny** [comment]
That's not going to work. If you're going to make changes to the underlying XML structure then you're going to need to understand how it is structured, which is a big lift.

How about something simpler like this:

```python
def add_new_docx(new_docx_path):
    document = Document("final.docx")
    document_to_append = Document(new_docx_path)

    document.add_page_break()

    for paragraph in document_to_append.paragraphs:
        document.add_paragraph(paragraph.text)

   document.save("new-final.docx")
```

**Comment by msloat450** [comment]
> That's not going to work. If you're going to make changes to the underlying XML structure then you're going to need to understand how it is structured, which is a big lift.
> 
> How about something simpler like this:
> 
> ```python
> def add_new_docx(new_docx_path):
>     document = Document("final.docx")
>     document_to_append = Document(new_docx_path)
> 
>     document.add_page_break()
> 
>     for paragraph in document_to_append.paragraphs:
>         document.add_paragraph(paragraph.text)
> 
>    document.save("new-final.docx")
> ```

Thank you for your help.  One issue with that would be with 'document.add_paragraph(paragraph.text)'.   It is only going to pass the text and not any tables etc.  How would you incorporate passing tables etc as well?  Would I need a separate for table statement to add those as well?

**Comment by scanny** [comment]
Yeah, so this is the reason why there is no "copy-between-documents" features in the library. Once you cross that line then you _do_ need to dive into the XML and that gets pretty complicated pretty fast with things like embedded images and hyperlinks and so forth that relate to external entities and need to get copied recursively and re-identified because the id from the old doc is not valid in the new doc etc.

You can do at least a little better than what I've shown though. Check out the brand-new feature `Section.iter_inner_content()` here: https://python-docx.readthedocs.io/en/latest/api/section.html#docx.section.Section.iter_inner_content

This allows you to do something like this:

```python
for section in document.sections:
    for item in section.iter_inner_content():
        if isinstance(item, Paragraph):
            do paragraph thing ...
        elif isinstance(item, Table):
            do table thing ...
```

Then you can copy paragraphs run-by-run, assigning bold and italic as it is in the original, probably style too if the documents have the same ones available.

On tables you can go cell-by-cell and add content the same way. Each cell contains one-or-more paragrahs.

This will break down when things get too complicated, but would get you further along.

However, be advised that this sort of thing, while intuitively straightforward, isn't something that `python-docx` is really equipped to handle. You might want to consider either a different approach to compiling documents, or going with one of the paid options that could possibly do these sorts of things (not cheap unfortunately).

**Comment by msloat450** [comment]
Thank you.  So, do you think if the docs I was working with only had simple fonts, tables, and maybe a image that Python-docx should be able to process them?  It might not look exactly like the original but fairly close?

Thank you again for your help.

**Comment by scanny** [comment]
I'd say so. If you can exercise _some_ control over how fancy the incremental report content is, you could definitely accomplish something interesting.

The image is going to be tough but maybe you can figure that out. It would be something like read the image from the other doc into a file-like object and then `.insert_picture()` at the right spot.
