### ISSUE TITLE
The cell's vMerge attribute may be incorrect

### ISSUE THREAD

**Issue by iclgg** [python-openxml/python-docx#1380]
When I attempt to process the table through the vMerge attribute of cells, I've noticed that the vMerge value for some cells should be 'continue', yet it actually appears as 'restart'.
When I use the code below, I noticed that the vMerge attribute value obtained for the same cell is different in two ways. Is this due to some design intention or is it an error?
```
    for table in doc.tables:
        for row in table.rows:
            tr = row._tr
            row_cell_tc = [tc for tc in tr.tc_lst]
            cell_tc = [cell._tc for cell in row.cells]
```

**Comment by scanny** [comment]
This has to do with the way `row.cells` works.

Check out this page in the docs and then if you still have questions let me know:
https://python-docx.readthedocs.io/en/latest/user/tables.html

Basically, `[tc for tc in tr.tc_lst]` with give you the actual value in the `w:tc` element. `cell in row.cells` gives you the "root" (top-left) cell for a spanned cell so vMerge for that will always be "restart" (when it exists).

Feel free to reopen if you end up with more questions after reading.

**Comment by nulix31** [comment]
It seems that there is another root cause to this issue:
I have a docx containing a table with cells merged vertically.
In the 'table' object, table._element.xml contains:
- cell xml for the first row:
```
    <w:tc>
      <w:tcPr>
      ...
        <w:vMerge w:val="restart"/>
      ...
      </w:tcPr>
      ...
    </w:tc>
```
- cell xml for the other rows:
```
    <w:tc>
      <w:tcPr>
        ...
        <w:vMerge/>
        ...
      </w:tcPr>
      ...
    </w:tc>
```

In the 'cell' object, cell._element.xml has the same content for all rows:
```
    <w:tc>
      <w:tcPr>
      ...
        <w:vMerge w:val="restart"/>
      ...
      </w:tcPr>
      ...
    </w:tc>
```
The `w:val="restart"` should only be present for the first occurrence of the merged cell. It seems that te code used to generate cell._element.xml overwrites the cell code extracted from the table._element.xml.
