### ISSUE TITLE
support w:color

### ISSUE THREAD

**Issue by microe** [python-openxml/python-docx#139]
I have a need to be able to look at the color of the text in a paragraph.

For example, I have a test question:
1. Which theory describes the entire earth, made of both living and non-living parts, as single system?
*red*a.  Gaia theory
b.  Evolution theory
c.  Law  of inheritance
d.  Law of production
e.  None of the above

I want to be able to see that the color is red (value ff2600). I tried to look through the code and stumbled on the CT_rPr class. It has a tag for w:color, but when I tried to set up an ```@property``` it said ```AttributeError: 'CT_RPr' object has no attribute 'color'```.

I am happy to take another stab at adding my own attribute, but I need a hint if I am going to get any farther.

**Comment by scanny** [comment]
Hi Erik, @virajkanwade has this working in a pull request here: https://github.com/virajkanwade/python-docx/commits/feature/styles

I'll be getting this into a minor release here probably in a couple weeks now that I've got the 0.8.0 release out. The API will change a little bit based on some discoveries we made working on this but it will be quite close.

Let me know if you need more to go on :)

**Comment by microe** [comment]
I was able to cherry pick the color part of the pull request and successfully install python-docx with that commit into a virtualenv. I can query the color using paragraph.style.font.color, but the color for every paragraph in the document reads (0, 0, 0) instead of (ff, 26, 0) - red for some paragraphs.

Thanks for the pointer, it opened up a new avenue. If you see anything I should be doing, let me know. I get the sense that I am looking at color from the wrong object.

**Comment by scanny** [comment]
Hmm, doesn't sound quite right, I think what you're looking for is `run.font.color`.

Most runs won't have any directly applied color, and should return `None` in that case, not (0, 0, 0) which is a valid color (black).

All directly-applied character formatting is applied at the Run level. The reason a paragraph style has a font property is it applies both paragraph and character formatting.

When a run doesn't have a specific value, i.e. returns `None`, that doesn't mean it doesn't have a color, it just means it doesn't have a directly-applied one. In this case it inherits the value from the style hierarchy, which is several layers deep, ending at the document defaults. We don't have functionality built-in yet to find the "effective" value (by traversing the style hierarchy for a run or whatever), mostly because it's a big job and we'll need to get further along on some infrastructural bits before that will be feasible.

**Comment by microe** [comment]
Ah ha! That did it. Now I can find text that has the font color ff2600 using the pull request above. Now I have another conundrum, background color. Any advice is much appreciated. Thank you so much for the help so far. It has been very helpful.

**Comment by scanny** [comment]
Added Font.color in release 0.8.3 today, Feb 19, 2015. User docs are here: http://python-docx.readthedocs.org/en/latest/user/text.html#font-color

If you submit your new question on background color in a new issue I'll be happy to respond.
