### ISSUE TITLE
Values in tables are being splitted into multiple rows if there is \n in them

### ISSUE THREAD

**Issue by edzakharyan97** [python-openxml/python-docx#1415]
i have a table in docx file. some values in table have "\n" in them. and when i apply this script:
```
path = "test.docx"
from docx import Document

doc = Document(path)
table = doc.tables[0]
for row in table.rows:
    for cell in row.cells:
        print(cell.text.strip())
        print("-------------------")
```
i see that values that have "\n" in them are being splitted into several rows. How to solve this issue?

Example:
for this table
![photo_2024-07-15_11-26-55](https://github.com/user-attachments/assets/9477bf28-94b1-4a67-832c-6a70d5471cc5)

column name "Category/Technical \n policy" is being splitted into two rows "Category/Technical" and "policy".

**Comment by manutheblacker** [comment]
You many need to replace \n by '\t" so everything stays on the same line.

**Comment by scanny** [comment]
`cell.text` contains a newline (`"\n"`) between paragraphs in that cell. So it appears that "Category/Technical" is one paragraph and "policy" is another.

You can avoid this be making it all one paragraph. Otherwise you'll need a strategy to accommodate newlines in the text.

Closing as this is the expected behavior.
