### ISSUE TITLE
Feature: Tab stops (left and right alignment on same line)

### ISSUE THREAD

**Issue by StAlphonso** [python-openxml/python-docx#157]
I have a document that needs text to be aligned on both the left and right side of the document on the same line. I believe this is accomplished in word using a right tab stop. For example, a contract that has underscore lines on both left and right side of the document for signatures, and wont spill over to the next line due to varying string lengths (for example, different names for the people signing the contract which would be under the underscore lines). Hope this makes sense and THANK YOU!

**Comment by scanny** [comment]
Hi All, just a note to let you know we've just finished up tab stop support due to the diligent work and generous spirit of @DKWoods. You can trial it by installing from feature/tabstops. Would love to get some feedback if you have a chance to try it out. Documentation is here:
https://github.com/python-openxml/python-docx/blob/feature/tabstops/docs/user/text.rst#tab-stops

.. and in the docstrings here:
https://github.com/python-openxml/python-docx/blob/feature/tabstops/docx/text/tabstops.py

This will appear in the next release.
