### ISSUE TITLE
add ability to add TAB stops from python-docx

### ISSUE THREAD

**Issue by bradyt** [python-openxml/python-docx#199]
An option to format a paragraph is to add TAB stops, especially one right aligned, and match with right margin. 

Would be nice to have this option from python-docx.

**Comment by scanny** [comment]
Hi All, just a note to let you know we've just finished up tab stop support due to the diligent work and generous spirit of @DKWoods. You can trial it by installing from feature/tabstops. Would love to get some feedback if you have a chance to try it out. Documentation is here:
https://github.com/python-openxml/python-docx/blob/feature/tabstops/docs/user/text.rst#tab-stops

.. and in the docstrings here:
https://github.com/python-openxml/python-docx/blob/feature/tabstops/docx/text/tabstops.py

This will appear in the next release.

**Comment by ArnaudCoulon** [comment]
> Hi All, just a note to let you know we've just finished up tab stop support due to the diligent work and generous spirit of @DKWoods. You can trial it by installing from feature/tabstops. Would love to get some feedback if you have a chance to try it out. Documentation is here:
> https://github.com/python-openxml/python-docx/blob/feature/tabstops/docs/user/text.rst#tab-stops
> 
> .. and in the docstrings here:
> https://github.com/python-openxml/python-docx/blob/feature/tabstops/docx/text/tabstops.py
> 
> This will appear in the next release.

To bad it's 404...

**Comment by scanny** [comment]
@ArnaudCoulon I've updated the links.

**Comment by ArnaudCoulon** [comment]
Great thanks a lot!

**Comment by DKWoods** [comment]
Yeah, URLs change over time, especially when features get moved into the 
main branch.  The current links are:

https://github.com/python-openxml/python-docx/blob/master/docs/user/text.rst#tab-stops

and

https://github.com/python-openxml/python-docx/blob/master/docx/text/tabstops.py

David
