### ISSUE TITLE
UnicodeEncodeError during doc.save()

### ISSUE THREAD

**Issue by repetilo-andrey** [python-openxml/python-docx#230]
Hello.
Here is traceback:
```
doc.save(save_path)
  File "docx/document.py", line 142, in save
    self._part.save(path_or_stream)
  File "docx/parts/document.py", line 128, in save
    self.package.save(path_or_stream)
  File "docx/opc/package.py", line 160, in save
    PackageWriter.write(pkg_file, self.rels, self.parts)
  File "docx/opc/pkgwriter.py", line 32, in write
    phys_writer = PhysPkgWriter(pkg_file)
  File "docx/opc/phys_pkg.py", line 141, in init
    self._zipf = ZipFile(pkg_file, 'w', compression=ZIP_DEFLATED)
  File "python2.7/zipfile.py", line 701, in init
    self.fp = open(file, modeDict[mode])
````

I recieve this error:
`zipfile in __init__
UnicodeEncodeError: 'ascii' codec can't encode characters in position 65-66: ordinal not in range(128).`

save_path is simple and contains unicode: 
`u'/home/my/path/to/directory/1234_text_ДД-123.docx'`

And text inside document contains unicode too.
Long time saving worked well, but now it fails and I cannot understand what can have influence on it.

Can you explain me please how to fix it?

**Comment by scanny** [comment]
I'm pretty sure it's the unicode characters in your filename. See if removing those fixes things. If that works we can look a little deeper to see what the problem is. It might be a coercion to String somewhere in there. The next step after that would be to call ZipFile() directly with your unicode filename and see if that works. If it does I'll have a look and see where it might be going wrong. Better paste in the code that sets the file name and calls save so I can see where all this starts.

**Comment by repetilo-andrey** [comment]
Well, removing unicode from file name fixes the problem.  Thanks, probably Issue can be closed. But I still can not understand why it worked earlier and leads to error now.
