### ISSUE TITLE
Unable to dynamically add attributes to Document objects

### ISSUE THREAD

**Issue by TonyBeswick** [python-openxml/python-docx#238]
Due to `__slots__` being defined on `docx.document.Document`, attributes cannot be dynamically added to documents.

I wish to create a method that returns a document object pre-formatted with some tables that the caller will later modify, I would like to reference these tables as attributes on the document so they can be accessed by name.

Can `__slots__` be removed from `docx.document.Document`?

**Comment by scanny** [comment]
Hi @TonyBeswick, I'm thinking you would be better off to compose a Document object in your own wrapper object rather than add additional fields to Document itself. The choice to use __slots__ on that an many other objects was a careful one and not one we're likely to reverse for this purpose. One of the things that happened quite a bit would be that folks would accidentally add new attributes by mistyping an attribute name or whatever, then wonder why their code didn't work the way they expected it to.

You can pass through any unrecognized attribute lookups to the Document object by using a __getattr__() method on your wrapper class.
