### ISSUE TITLE
Iterating over table.row_cells returns creates copies of cell objects

### ISSUE THREAD

**Issue by dibsonmuad** [python-openxml/python-docx#330]
First, thanks for this package! Please take a look at the object addresses when iterating over row_cells. Why do the addresses keep changing? Looks like a copy is being created each time. Why? This doesn't seem intuitive.

```python
Iterate over the cells in row 58.
>>> for c in t.row_cells(58):
	print(c)
<docx.table._Cell object at 0x0000000003A710B8>
<docx.table._Cell object at 0x00000000039D3CC0>
<docx.table._Cell object at 0x0000000003A6F8D0>
<docx.table._Cell object at 0x0000000003A6F908>


c = t.row_cells(58)[0]
c.text = 'blah'
t.row_cells(58)[0].text
''

I would expect cell 0 of row 58 to contain 'blah'

Iterate again.

>>> for c in t.row_cells(58):
	print(c)
<docx.table._Cell object at 0x0000000003A6F828>
<docx.table._Cell object at 0x0000000003A6F860>
<docx.table._Cell object at 0x0000000003A6F898>
<docx.table._Cell object at 0x0000000003A6F940>
Whaaaat? Why are they different? 


>>> t.row_cells(58)
[<docx.table._Cell object at 0x0000000003A6F780>, <docx.table._Cell object at 0x0000000003A6F7B8>, <docx.table._Cell object at 0x0000000003A6F7F0>, <docx.table._Cell object at 0x0000000003A6FC18>]

This is the very next call.

>>> t.row_cells(58)
[<docx.table._Cell object at 0x0000000003A6F748>, <docx.table._Cell object at 0x0000000003A6FC50>, <docx.table._Cell object at 0x0000000003A6FC88>, <docx.table._Cell object at 0x0000000003A6FCC0>]

**Comment by scanny** [comment]
A `_Cell` object is what is called (in this project) an *element proxy*, meaning it provides API functionality to what is essentially an `lxml` object representing an XML element.

A `_Cell` object is created when needed to satisfy an API call, such as row.cells[58]. If you call that twice, you'll get two different objects; however, the underlying `lxml` object will be the same in each case. No new table cells are created.

If you want to tell whether two `_Cell` objects are wrapping the same cell element, you can use:

```python
cell_1._tc == cell_2._tc
```

Which will evaluate `True` if both are wrapping the same cell element.

A `_Cell` object does not store any data other than the `tc` element reference. Any properties read or write directly to the XML object. So you should think of the `_Cell` object as a handy wrapper of functionality over the XML element rather than a separate data item.
