### ISSUE TITLE
Win 10 Install

### ISSUE THREAD

**Issue by Mwanafunzi** [python-openxml/python-docx#336]
Having a nightmare trying to install docx on win10 with python 2.7

pip and setup.py install both fail, after going round in circles googling a range of errors, I seem to get to a problem with libxml, most persistent error says "no module named lxml"    and/or "....is libxml2 installed ?"

I installed lxml from ms, it seemed to go in ok, but no effect on docx installation

Deeply frustrating! It all worked beautifully on Mac OS for development, but now I can't use it on the target machine!   I don't suppose there is a simple 'complete package' for win 10? I am even wondering about deploying it via a linux vm, which seems crazy overkill to run a few lines of python.

**Comment by scanny** [comment]
What is the python installation you're using? If it's anaconda or something I believe they have their own location for keeping packages so an lxml install might go in a place it doesn't look.

This is almost certainly an lxml install problem. I'm not sure what "installed lxml from ms" means, but you'll want to do a binary package install of lxml rather than try to compile it as would happen quite painlessly on the Mac. http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

If you're using anaconda or some other "packaged" python you should search on "anaconda lxml" or whatever to find out how other folks have gotten that to work.

**Comment by Mwanafunzi** [comment]
It is python 2.7.12 from https://www.python.org/downloads/windows/

"but you'll want to do a binary package install of lxml rather than try to compile it as would happen quite painlessly on the Mac. http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml"

Ah, yes, I got there in my googling, but lost my nerve over what to download and what to with it having downloaded it.  It seemed too far into blindly following googled advice on someone else's machine!

**Comment by scanny** [comment]
I expect it's one of these two:
lxml‑3.6.4‑cp27‑cp27m‑win32.whl
lxml‑3.6.4‑cp27‑cp27m‑win_amd64.whl

The cp standing for CPython, and the 27 meaning 2.7. I expect Windows 10 is 64 bit (so the second one) but you'll have to work that out :)

**Comment by Mwanafunzi** [comment]
Great, thanks!   Will give it a go.

**Comment by lyncas** [comment]
I ran into the same issues on Win 10.   The lxml  whl files worked for me.  It took a lot of google searching on stackexchange to find a solution.   Hopefully more people can find this faster than me.  Thanks @scanny

**Comment by scanny** [comment]
Glad you got it working @lyncas :)
