### ISSUE TITLE
duplicate cells returned from row.cells

### ISSUE THREAD

**Issue by daveoloughlin** [python-openxml/python-docx#344]
The following code iterates through rows in the attached docx. Multiple cell instances have the the same text values somehow.
[pu.docx](https://github.com/python-openxml/python-docx/files/685618/pu.docx)
 
```python
import docx
import os

doc = docx.Document('pu.docx')
for table in doc.tables:
    rowNo = 0
    for row in table.rows:
        cellNo = 0
        for cell in row.cells:
            print 'rowidx = {0} cellidx = {1} text ={2} '.format(rowNo, cellNo, cell.text)
            cellNo += 1
        rowNo += 1
```

**Comment by scanny** [comment]
This is the expected behavior when there are merged cells. If you want to get just the "visual" cells, you need to get the merge information for the cells and skip the merged width number of cells.

While this may seem less than an optimum design for the API, I remember there was a lot of deliberation that went into it and it was the best of the possible options. It would compromise other operations to make it "automatically" jump to the start of the next visual cell.

**Comment by scanny** [comment]
Apologies @daveoloughlin, Github seems to have eaten my response from last week.

I think you want something like this:

```python
def iter_visual_cells(row):
    prior_tc = None:
    for cell in row.cells:
        this_tc = cell._tc
        if this_tc is prior_tc:  # skip cells pointing to same `<w:tc>` element
            continue
        yield cell
        prior_tc = this_tc
```

**Comment by daveoloughlin** [comment]
Thanks very much. Much simpler ;-)
