### ISSUE TITLE
how to copy a docx into a template with headers?

### ISSUE THREAD

**Issue by schoreZ** [python-openxml/python-docx#364]
I am trying to add headers to a series of docx files. But since python-docx does not provide header manipulation, I'm thinking to copy the source files' contents (with all its figures, images, tables styles, etc.) to a template file with a header, as the docx documentation says it politely preserves the headers of an opened docx.

  So I will do this in two steps:
  1) read all the contents from the source docx in sequence.
  2) wrote all the contents with its formats to the existing template file.

  But having read the documentation, googled solutions, I have problems that the documentation doesn't tell me:

  1) What should I 'copy' from the source file? not paragraphs. Is it elements, blocks, parts, sections, or something else? 
  2) How do I iterate these 'to copy' objects? and how do I put them into a new file?

I see some related problems using methods that do not exist in the docx 0.8.6 documentation, such as 
paragraph._element
p.getparent().remove(p)
p._p = p._element = None
document.body.append(element)
xpath
etc. 

  Is it because they are previous version features that will not be supported in the future? 
  If they are essential, where should I find their usage?

Thank you very much.

**Comment by scanny** [comment]
`Paragraph._element` is a "private" variable, which is why it doesn't appear in the API documentation. "Private" here reflects its role as an implementation detail, and these can be changed at will as required to add new features or refactor or whatever. So theoretically this is subject to change without notice, but I'd say these `._element` names are very unlikely to change going forward. Any time you use "internals", or more precisely "implementation specifics", you risk breakage when you upgrade, but I'd put use of these at the low end of that risk spectrum.

The `.getparent()`, `.remove()`, and `append()` methods are on `lxml.etree._Element`, which is the library `python-docx` uses for XML manipulation. You can find the lxml API documentation online here http://lxml.de/, look for 'API Documentation' on the left hand navigator to access the latest version.

**Comment by schoreZ** [comment]
ok, I will check this out, thanks again :)

**Comment by scanny** [comment]
Header and footer support will be released with v0.8.8 in the next day or two. Until then a working version is available on the `spike-header` branch.

**Comment by schoreZ** [comment]
Mr. Scanny, 
  Just want to apologize to you.

  I do not know if it's necessary to clear this up, but I had really done it wrong.

  At the time I was opening this issue, I barely knew what git version control is and its relationship with github. I had no idea what an **issue** is, but took for granted that it looked like a **forum**. As for the meaning of **closing** an **issue**, that's beyond my comprehension then...

  I feel sorry that this may have caused some grimaces on your side, just because my stupidity.

  Good news is that I'm still using your awesome module in my tiny projects, and will recommend others to use it.

  Wish you have a nice day.

Schore

**Comment by scanny** [comment]
No worries @schoreZ  :)
