### ISSUE TITLE
Question about paragraph spacing

### ISSUE THREAD

**Issue by sanjuroj** [python-openxml/python-docx#374]
I was sent a short docx document that, when I look at it from within MS Word (Mac version 15), has 10pt of paragraph spacing after each paragraph.  However, when I examine the doc using the python-docx API (v 8.6), the paragraph spacing doesn't appear to be set.  This is only a problem for this document so far, I can see the paragraph spacing when using python-docx on other docx files that I receive.  This is the testing code I used:

```
rpt = Document('./testDoc.docx')

for rptPara in rpt.paragraphs:
    print(rptPara.text)
    print(rptPara.paragraph_format.space_after)
    print(rptPara.paragraph_format.space_before)
    print(rptPara.style.name)
    paraStyleName = rptPara.style.name
    print(rpt.styles[paraStyleName].paragraph_format.space_after)
    print(rpt.styles[paraStyleName].paragraph_format.space_before)
```

For each paragraph, the print statements produce
```
<Paragraph text here>
None
None
Normal
None
None
```

Am I looking in the wrong place for the spacing or is there another property that I should be looking at?  

Thanks!

**Comment by scanny** [comment]
In general, paragraph and font attributes for a given paragraph or run (respectively) are calculated by Word at run time by traversing the style hierarchy. This works a bit like Cascading Style Sheets (CSS) does for HTML. What you seem to be looking for is the *effective* paragraph spacing, which is the final result of this calculation/traversal.

The hierarchy starts out the way you've discovered so far, which is that directly applied formatting wins in every case, but an attribute is inherited from its style if not directly applied.

However, there are additional levels. A style can be "based on" another style, and inherits from that style any attributes it does not itself define. So that would be the next step. I believe there is a `.base_style` property available on both CharacterStyle and ParagraphStyle.

Then, I believe there is a document default style (one of each type, Paragraph, Character, etc.). It's been a while since I've had my head into this and it's not terrifically well documented on the web, so you may have to dig a bit. But as I remember, any attribute not defined by the explicit style graph is inherited from the document default style. I don't believe there is a property on style defined for this, but you could examine the style XML for the `w:default` property, maybe something like this:

```python
from docx.oxml.ns import qn  # short for "qualified name"

style_element = style.element
print(style_element.xml)
print(style_element.get(qn('w:default')))  # prints a boolean value or None if no such attr present
```

Finally, I believe there is a "built-in" set of defaults which rule in the case where no style of any type explicitly defines a setting. I believe these are hard-coded into Word, although themes may come into play for font and color choices.

So I expect if you dig a little deeper you'll find what you're looking for. I expect it will take a little experimentation to discover the exact rules Word uses, unless you have better luck than me with Google :)

**Comment by sanjuroj** [comment]
Thanks! That was a very clear description, and even that little bit is way more than I wanted to know about docx xml :-)  

I added these to the test script.
```
print(rpt.styles[paraStyleName].base_style)
style_element = rpt.styles[paraStyleName].element
styles = rpt.styles.element
print(style_element.xml)
print(style_element.get(qn('w:default')))  # prints a boolean value or None if no such attr present
print('=====================')
print('styles xlm', rpt.styles.element.xml)
print('styles spacing', styles.get(qn('w:spacing'))) 

```
The result was

``` 
None
1
<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
...
w:default="1" w:styleId="Normal">
  <w:name w:val="Normal"/>
  <w:qFormat/>
  <w:rsid w:val="007F1918"/>
</w:style>
=====================

<A blob of xml for the styles element>
```

In that big styles xml blob I noticed something.  In the document where I haven't been able to find the spacing, there was this section:
```
...
    <w:pPrDefault>
      <w:pPr>
        <w:spacing w:after="200" w:line="276" w:lineRule="auto"/>
      </w:pPr>
    </w:pPrDefault>
  </w:docDefaults>
```

The doc where the paragraph spacing occurred further down the chain didn't have the `<w:spacing` tag.  So I wonder if that might be it?  If so, I just need to figure out how to get it programatically. 

Thanks for your clear explanation, I think it got me to the right place(?).

**Comment by scanny** [comment]
I believe you've found it. 200 twips is the same as 10pt, and this setting would provide the default for the entire document, regardless of where in the XML it appears. So this would be the fourth level I spoke about above, the document-wide default.

If you can provide more of the context XML in which it appears (its ancestors in particular), I can help you work out the XPath expression to locate it and you can read it using lxml calls. It would go something like this:

```python
def document_default_spacing(document):
    document_elm = document.element
    spacings = document_elm.xpath('./w:docDefaults/w:pPrDefault/w:pPr/w:spacing')
    if len(spacings) == 0:
        print('No document default spacing defined')
        return
    spacing = spacings[0]
    print('space after twips == %s' % spacing.get(qn('w:after'))
```

**Comment by sanjuroj** [comment]
Based on the code you provided above, this seems to do the trick:
```
styles = rpt.styles.element
spacings = styles.xpath('/w:styles/w:docDefaults/w:pPrDefault/w:pPr/w:spacing')
print(spacings[0].get(qn(('w:after'))))
```

This is the first part of styles.element.xml, for posterity.
```
<w:styles xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" mc:Ignorable="w14 w15">
  <w:docDefaults>
    <w:rPrDefault>
      <w:rPr>
        <w:rFonts w:asciiTheme="minorHAnsi" w:eastAsiaTheme="minorHAnsi" w:hAnsiTheme="minorHAnsi" w:cstheme="minorBidi"/>
        <w:sz w:val="22"/>
        <w:szCs w:val="22"/>
        <w:lang w:val="en-US" w:eastAsia="en-US" w:bidi="ar-SA"/>
      </w:rPr>
    </w:rPrDefault>
    <w:pPrDefault>
      <w:pPr>
        <w:spacing w:after="200" w:line="276" w:lineRule="auto"/>
      </w:pPr>
    </w:pPrDefault>
  </w:docDefaults>
```
Thanks for all your help!

**Comment by scanny** [comment]
Glad you got it working :)
