### ISSUE TITLE
why my IDE can't Auto-Complete for python-docx?

### ISSUE THREAD

**Issue by qianshuijun** [python-openxml/python-docx#378]
when i use python-docx , my IDE ,like pycharm  wing , can't Auto-Complete it.
this code
````
from docx import Document

asd = Document()
asd.add_heading("test")
asd.save("cao.docx")
````

when i typing asd.     add_heading can't Auto-Complete.   

```
from docx.document import Document  

asd = Document()
asd.save()
```
this code can Auto-Complete 
but atention 
> TypeError: __init__() missing 2 required positional arguments: 'element' and 'part'

**I am sorry for my poor english**

**Comment by scanny** [comment]
This question would be better posted on StackOverflow. This issues list is for suspected bugs and feature requests.

**Comment by satyendrakumarsharma** [comment]
As a matter of fact, `docx.Document(...)` is actually a method, which returns an object of the `docx.document.Document` class.
Perhaps they should have named this method by following the naming convention, say something like _docx.create_document(...)_.
You hve been trying to treat this (`docx.Document()`) method as a class.

Hence, you shall use both the following imports, in order to get the visibility of the contents of `docx.document.Document` class:

> from docx import Document
> from docx.document import Document

https://stackoverflow.com/a/52466366/1795463
