### ISSUE TITLE
Accessing adjacent properties of different types in Document object

### ISSUE THREAD

**Issue by injune16** [python-openxml/python-docx#412]
The situation I am at right now is that I want to locate a table which the content should be instructed by a paragraph right above it. In another word I should be given a string that appears in a paragraph and is expected to get a reference of the table right below it. In the docs both tables and paragraphs are block items but Document objects don't have a "blocks" property, and we don't have a "BlockItem" interface. Is there any way to work around?

**Comment by willem-tee** [comment]
I think I am in the same page and don't know how to work it out. My objective is to be able to read "line by line" and interact with it, it being a paragraph or a table. This is so because they are directly related and being able to read both, one after each other is key. 

I can iterate through the Doc with say, for loops, on tables or on paragraphs but they are incompatible with each other meaning the for loop will ignore the counterpart.

Anyone has any idea on that?

W

**Comment by scanny** [comment]
Search this issues list on `iter_block_items`.

Especially this one: #40.
