### ISSUE TITLE
page number in header

### ISSUE THREAD

**Issue by galerivs** [python-openxml/python-docx#640]
how can i add page number in the header ?
and how to know how many pages my document have

**Comment by Miamoto-Musashi** [comment]
I need the same info; any info from the developer?

thanks

**Comment by scanny** [comment]
I believe you'll find that current page-number is implemented in Word as a _field_. There is no API support for fields so far in `python-docx`.

On the "how many pages" question, that's not something `python-docx` will (ever) be able to tell you since pagination is performed by the client application (e.g. Microsoft Word) and it only knows that at runtime (it's not written to the file).
