### ISSUE TITLE
Cm() measurements aren't stable

### ISSUE THREAD

**Issue by iansparks** [python-openxml/python-docx#687]
I've been puzzling the fact that measurements in Cm are not stable in docx.

Running this snippet gives me: 

AssertionError: 3599815 !== 3600000

Seems to be some kind of precision error on Cm measurements?

```python 
from docx import Document
from docx.shared import Cm, Inches

doc = Document()
# Inches are stable
doc.sections[0].page_width = Inches(10)
assert doc.sections[0].page_width == Inches(10)

# Cms are not stable
doc.sections[0].page_width = Cm(10)
assert doc.sections[0].page_width == Cm(10), f"{doc.sections[0].page_width} !== {Cm(10)}"
```

**Comment by scanny** [comment]
Hmm, interesting. That seems like more error than I would have expected. But I'll bet I know where it's coming from. Page width is stored in integer twips (1/20th of a point, so 1/1440 inch or 635 EMU). I expect you'll find that round-tripping through page-width will give you an error of up to 634/2 = 317 EMU error regardless of the unit.

Integer inches just happen to fall on even twips boundaries. If you try Inches(1.36) you'll also see a round-trip error.

**Comment by iansparks** [comment]
Thanks. It's definitely Twip related,
```
print(Twips(Emu(360000).twips).emu)    # 360045
print(Cm(Emu(360000).cm).emu)          # 360000
print(Inches(Emu(360000).inches).emu)  # 360000
print(Pt(Emu(360000).pt).emu)          # 360000
```
This extends to all places where width/heights are used but as far as I can see Word displays the intended measurement so its just an error of reporting. Not sure anything much can be done about it?

**Comment by scanny** [comment]
Well, the actual underlying value in Word is in twips. Like in the XML it would be `width="1440"` and that would mean an inch. Consequently, there's no way to specify exactly 1 cm and so on. The underlying system is integral (no fractional twips) and based on an inherently English/inch unit. I suppose it's because points and therefore twips are a traditional printing unit.

I suppose on paper, an error of .00035 inch is rarely a problem and I'm not even sure how you would detect it. So it's probably only when folks are doing what we're doing in software tests and so on that it causes a real problem. I expect in the Word UI they round to the nearest .1mm or something when it's set to metric.

**Comment by iansparks** [comment]
Thanks for looking at this. I think this tread documents it well enough for anyone else who is puzzled in future. Great library, really appreciate it.
