### ISSUE TITLE
Python Docx - Certain cells in a table not detected

### ISSUE THREAD

**Issue by LiaqatMoideen** [python-openxml/python-docx#757]
Hello,
I am developing a python script using python docx. I need to extract information from docx table. However, some of the cells are not detected by my script. The cell is not a merged one. Please let me know why this has happened and possible solutions. Thanks in advance.

Regards,
Liaqat Moideen

**Comment by gagmeng** [comment]
Maybe you should attach your docx file and python script.

**Comment by matthewgdv** [comment]
I'm also having this issue, particularly when cells are only filled with things other than ordinary text (such as a datepicker widget or dropdown control). Here's an example.

For the following file:

[issue.docx](https://github.com/python-openxml/python-docx/files/3950479/issue.docx)

This code:

```python
[[[cell.text for cell in row.cells] for row in table.rows] for table in document.tables[:-1]]
```

returns:

```python
[[['Row1 Key', 'Row1 Value'],
  ['Row2 Key', 'Row3 Key'],
  ['Row3 Value', 'Row4 Key'],
  ['Row4 Value']]]
```

**Comment by scanny** [comment]
The problem in your case is that there is no second cell (directly) under the second row (`rows[1]`); it is encapsulated in a `<w:sdt>` element.

```xml
      <w:tr ...>
        <w:tc>
          ...
          <w:p>
              ...
          </w:p>
        </w:tc>
        <w:sdt>
          <w:sdtPr>
            <w:alias w:val="From email address"/>
            <w:tag w:val="From email address"/>
            <w:id w:val="1616255234"/>
            <w:placeholder>
              <w:docPart w:val="06608B2528D74F1DB26E6E9DC1685AB5"/>
            </w:placeholder>
            <w:dropDownList>
              <w:listItem w:displayText="Row3 Controlled Value" w:value="Row3 Controlled Value"/>
            </w:dropDownList>
          </w:sdtPr>
          <w:sdtContent>
            <w:tc>
                ...
              <w:p>
                ...
                <w:r>
                  <w:t>Row3 Controlled Value</w:t>
                </w:r>
              </w:p>
            </w:tc>
          </w:sdtContent>
        </w:sdt>
      </w:tr>

```

You can get to the enclosing `<w:tr>` element via `row._element` or `row._tr` and XPath from there or whatever method suits best.

From the XML perspective, one way to look at this is there _is_ no column-2 cell in the second row; instead there is a cell data control. If we changed the API to produce this object instead of a cell, that would complicate things for the majority (and especially beginner) user who don't have these cases and perhaps struggles with the document and table complexity as it is.

I'm sure there's a clever solution that preserves the "least-surprise" behavior while still allowing access to the control, but I don't see that feature coming anytime soon.

One idea might be to write a row-cells accessor of your own that used XPath to find the `w:tc` elements wherever they might be "nested" and construct a `_Cell` object for each of those. Be aware however that a cell enclosed in a container may appear more than once, like before and after for an unaccepted revision perhaps, so while that method would work for this case, results may not always be as you expect.

**Comment by LiaqatMoideen** [comment]
[List.docx](https://github.com/python-openxml/python-docx/files/4034674/List.docx)
Hii,
Please find the document attached. Following is the piece of code

<beginning of code>
import sys 
import re
import os
import docx

from docx import Document
f_name = "./List.docx"
try:
    wordDoc = Document(f_name)
except IOError:
    print ("\n*** %s : Word Document NOT found.\n"%(f_name))
tables= wordDoc.tables
for t in range(0,9,1):
    print (tables[1].rows[t].cells[0].text)

<end of code>

 following is the print result

Item
ham
glass
ring
keys
75
1
Juice
coffee

As you can see, it has not detected certain cell[0] elements. Instead cell[1] or cell[2] are printed for row 4,5,6 ..row 7 is skipped. I am using python 3.7.4 and my word document version is Microsoft word 2013 (15.0.5197.1000) MSO (15.0.5172.1000) 32-bit. Please let me know the fix.

Thanks & Regards,
Liaqat Moideen

**Comment by LiaqatMoideen** [comment]
Hii,


> [List.docx](https://github.com/python-openxml/python-docx/files/4034674/List.docx)
> Hii,
> Please find the document attached. Following is the piece of code
> 
> import sys import re import os import docx
> from docx import Document
> f_name = "./List.docx"
> try:
> wordDoc = Document(f_name)
> except IOError:
> print ("\n*** %s : Word Document NOT found.\n"%(f_name))
> tables= wordDoc.tables
> for t in range(0,9,1):
> print (tables[1].rows[t].cells[0].text)
> 
> following is the print result
> 
> Item
> ham
> glass
> ring
> keys
> 75
> 1
> Juice
> coffee
> 
> As you can see, it has not detected certain cell[0] elements. Instead cell[1] or cell[2] are printed for row 5,7 ..row 6 and 8 are skipped. I am using python 3.7.4 and my word document version is Microsoft word 2013 (15.0.5197.1000) MSO (15.0.5172.1000) 32-bit. Please let me know the fix.
> 
> Thanks & Regards,
> Liaqat Moideen

**Comment by LiaqatMoideen** [comment]
ignore the missing indentation.  Proper indentation is there for the code while executed :-)
