### ISSUE TITLE
docx.opc.exceptions.PackageNotFoundError

### ISSUE THREAD

**Issue by abodsakah** [python-openxml/python-docx#758]
I am trying to read a header from a word document using python-docx and watchdog. What I am doing is, whenever a new file is created or modified the script reads the file and get the contents in the header, but I am getting an
`docx.opc.exceptions.PackageNotFoundError: Package not found at 'Test6.docx'
`
error and I tried everything including opening it as a stream but nothing has worked, and yes the document is populated. For reference, this is my code.
**main.py**
`import time
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import os
from docx import Document

class Watcher:

    def __init__(self):
        self.observer = Observer()

    def run(self):
        event_handler = Handler()
        self.observer.schedule(event_handler,path= r'../../../', recursive=True)
        self.observer.start()
        try:
            while True:
                time.sleep(5)
        except:
            self.observer.stop()
            print ("Error")

        self.observer.join()

    class Handler(FileSystemEventHandler):

    @staticmethod
    def on_any_event(event):
        if event.is_directory:
            return None

        elif event.event_type == 'created':
            # Take any action here when a file is first created.
            path = event.src_path
            extenstion = '.docx'
            base = os.path.basename(path)

            if extenstion in path:
                print ("Received created event - %s." % event.src_path)
                print(base)
                doc = Document(base)
                print(doc)
                
                doc = Document(base)
                section = doc.sections[0]
                header = section.header
                print(header.paragraphs[0].text)
              

        elif event.event_type == 'modified':
            # Taken any action here when a file is modified.
            path = event.src_path
            extenstion = '.doc'
            base = os.path.basename(path)
            if extenstion in base:
                print ("Received modified event - %s." % event.src_path)
                print(base)

                doc = Document(base)
                section = doc.sections[0]
                header = section.header
                print(header.paragraphs[0].text)

if __name__ == '__main__':
    w = Watcher()
    w.run()`

Tried to change the extension from doc to docx and that worked but is there anyway to open docx because thats what i am finding.

another thing. When opening the ".doc" file and trying to read the header all i am getting is

`
<docx.document.Document object at 0x03195488>
<docx.section._Header object at 0x0319C088>
`

and what i am trying to do is to extract the text from the header

**Full error list:**
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\watchdog\observers\api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\watchdog\observers\api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\watchdog\events.py", line 322, in dispatch
    self.on_any_event(event)
  File "c:/Users/abdsak11/OneDrive - Lärande/Dokument/GitHub/word-automation/main.py", line 65, in on_any_event
    doc = Document(base)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\docx\opc\package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\docx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\docx\opc\phys_pkg.py", line 32, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at 'test 1.doc'`

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests.

Could be the document is in the pre-Word 2007 binary format; .doc (as opposed to .docx) files typically are.

**Comment by andreanndrade10** [comment]
I think this module has a bug in Ubuntu 20.04 TLS;

File "/home/alla/.local/lib/python3.8/site-packages/docx/opc/phys_pkg.py", line 30, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at 'teste.docx'

**Comment by SanJacintoJoe** [comment]
Ya I encountered the same issue.

**Comment by Fagtoy** [comment]
has it been solved? just encountered the same issue

**Comment by abubelinha** [comment]
@scanny I guess some of these cases could be just a wrong error message.

When the document (.docx file) does not exist, the error reported when trying to open it is "Package not found"
Shouldn't it be better to say "File not found"?

I thought I was having an error on importing the package. 
But in my case it was just an error in the .docx file name.

**Comment by scanny** [comment]
@abubelinha Well, "wrong" is a pretty strong word. "Potentially confusing" I'll grant you though. In the Open Packaging Convention (OPC), a .docx file is known as a "package". The fact that an actual .docx file is a zip file is incidental. Packages don't have to be zip archives. They can be a directory tree structure or even something served over a network, piece-by-piece (part-by-part). The part of the code that raises this error doesn't know and shouldn't need to know what form the package is in this case.

All that said, it could say `OPC Package not found at ...` which might partially avoid confusing an OPC package with a Python package.

As far as distinguishing between "file not found" and other possible problems, have a look at the code this exception comes from: https://github.com/python-openxml/python-docx/blob/master/docx/opc/phys_pkg.py#L22-L36

There are four situations implemented so far; the `docx` parameter to `Document(docx)` is:

* absent (default "empty" package is loaded)
* is a str path to a directory ("expanded" (unzipped) .docx is loaded from that directory)
* is a str path to a .docx file (Zip archive containing the OPC package)
* is a file-like object (e.g. BytesIO) containing a Zip archive which is an OPC package)

The ambiguity arises when it is a string. This error arises when that "path" is not a directory and is not a zipfile. If it is neither of those, which did the user mean? Is it they misspelled the directory they wanted or there is neither a file nor a directory at that path or there is a file but it isn't a zip file or is otherwise not a loadable OPC package?

On thinking about this long enough to write this, it does occur to me we could trap the case where there is _nothing_ at that path, like neither a directory nor a file, and maybe raise "No file or directory at {path}". And I suppose we could go one further when there is a file there but it is not a zipfile and say something like "File at {path} is not a valid .docx file. Note that .doc (pre-Word 2007) files are not supported". I suppose we'd also need a case for "is zipfle but does not contain a valid OPC package".

Anyway, if you want you can add a separate issue for this entitled "Improve PackageNotFoundError messages" and we may look to improve that next time we're in there.

**Comment by abubelinha** [comment]
Thanks for the detailed explanation, and sorry about having  the _wrong_ word.
I didn’t intend it to sound strong, just to bring attention to a possible source of confussion.
Now that you are aware f it, I don’t think this deserves a new 
Thanks a lot again

**Comment by dongshm** [comment]
Be careful of the file path! Make sure that it is correct. I solved the same problem by correcting the path.

**Comment by zhelun333** [comment]
> Be careful of the file path! Make sure that it is correct. I solved the same problem by correcting the path.

yep    mine is the wrong path
