### ISSUE TITLE
Some characters are lost when I use Document().paragraphs[].text

### ISSUE THREAD

**Issue by hawksun123** [python-openxml/python-docx#803]
Hi @scanny 
This weird thing happens on the attached word file 'sample.docx'.
For example:
`doc = Document('sample.docx')`
`doc.paragraphs[14].text`
-> The result is 'Versionfor ' instead of 'Version 2.5.4 for XXXXX'
-> There are 6 Bullets under 'New and enhanced features' but 2 of them are missing. That is, the following text return nothing but should have 'Added the option to enable or disable Correctable Error Logging in the Memory Settings of the System BIOS Settings.' and 'Enhanced the Lifecycle error messages due to correctable memory errors. You will need to upgrade both the BIOS and iDRAC firmware to make sure that the new messages display correctly in the Lifecycle logs.'
`doc.paragraphs[43].text`
`doc.paragraphs[44].text`
`doc.paragraphs[45].text` 
`doc.paragraphs[46].text`   
`doc.paragraphs[47].text` 

But the content shows correctly when I open it with MS word in Office 365, please advise, thanks a lot.
[Example.docx](https://github.com/python-openxml/python-docx/files/4394446/Example.docx)

**Comment by scanny** [comment]
This can happen when parts of the paragraph (runs, etc.) are enclosed in other "wrapper" objects, like revision-marks in particular. If you have a search around that topic you'll see it comes up from time to time. You can try accepting all revisions, which might work, otherwise you'll need to inspect the XML and see what the particular enclosing elements are.
