### ISSUE TITLE
Replacing run.text without losing the image

### ISSUE THREAD

**Issue by Sheldenshi** [python-openxml/python-docx#838]
I am working on a script that translates documents. 

`Code:

			for run in paragraph.runs:
				run_text = run.text
				paragraph_runs.append(run_text)
				run.text = ""
			translated_text = translate("".join(paragraph_runs))
			paragraph.runs[0].text = translated_text`
An example is that 
<img width="654" alt="Screen Shot 2020-07-06 at 8 56 12 PM" src="https://user-images.githubusercontent.com/54699492/86707014-5c3da980-bfcc-11ea-9cb3-b7cc6e147a92.png">
for example I have this document, after running the program, it becomes
<img width="407" alt="Screen Shot 2020-07-06 at 8 57 33 PM" src="https://user-images.githubusercontent.com/54699492/86707137-7bd4d200-bfcc-11ea-90d2-384b6bc687dc.png">

I am wondering if there is a way I can replace the text without losing the image

**Comment by brasky** [comment]
The problem is you are going through every paragraph but I believe that image is a paragraph that you're modifying. Here's my PoC which hopefully explains it:

Here you can see the commands I used to test this:

![image](https://user-images.githubusercontent.com/3758126/90343551-5de48f00-dfc6-11ea-95d9-8844752761b8.png)


Here are the output documents: 
![image](https://user-images.githubusercontent.com/3758126/90343555-75bc1300-dfc6-11ea-8d64-51e831c177ce.png)



A simple solution would be when you are looping through paragraphs to check if paragraph.text is empty.
