### ISSUE TITLE
feature: Paragraph.text includes hyperlink text

### ISSUE THREAD

**Issue by SebasSBM** [python-openxml/python-docx#85]
When getting Document.paragraphs objects, their text method doesn't include hyperlinks in the output. The one with this problem posted his question here:

http://stackoverflow.com/questions/25228106/how-to-extract-text-from-an-existing-docx-file-using-python-docx/25228787#25228787

I've been reading the documentation of python-docx for several hours and didn't find any property or method useful to resolve this. Maybe some class should be created, or some methods should be appended to an existing class to achieve this.

I barely know something about python-docx API. I knew of it's existence trying to help some people in stackoverflow.com with their problems. I don't even know how Windows' DOCX format works (I tried to open it with an hexadecimal editor to try to figure it out, and I just don't get it :P). But I'm skilled with logic problems and I've got good skills with Python scripting. I'd like to help if there's something I can do.

**Comment by mikkleini** [comment]
Hi,
python-docx is a great tool that i just discovered. However, i also faced the missing hyperlink text problem right away.
Please solve it.

**Comment by mikkleini** [comment]
Ok, i think i faced the Python 2/3 issue. Here's something which works on Python 3.4:

```python
def remove_hyperlink_tags(xml):
    import re
    text = xml.decode('utf-8')
    text = text.replace("</w:hyperlink>","")
    text = re.sub('<w:hyperlink[^>]*>', "", text)
    return text.encode('utf-8')
```

**Comment by funkycode** [comment]
any schedule for that one?

**Comment by herrera78** [comment]
I used the code at https://gist.github.com/etienned/7539105#file-extractdocx-py and supplied the path and get hyperlink texts as I need

**Comment by desecho** [comment]
@scanny Please add your comments concerning #377. It seems to work correctly and provides the functionality described in this issue.

**Comment by sanjuroj** [comment]
I'd like to take a crack at adding this feature, but I'm a relatively inexperienced developer, especially on these kinds of large projects, and I'm going to have a lot of questions along the way.  If it seems like it would be too much to help me in this effort, please let me know and I'll leave it be.  

I'm curious if there is a step-by-step contributor guide somewhere that I could follow.  I can see several other issues where parts of the process have been outlined (#261, #278, #394) but I haven't seen a consolidated guide. I'm happy to start to make one as I go along but didn't want to duplicate effort if a guide already exists somewhere.  I'm also wondering what the best place is to discuss what programmatic approach to take, here or in a pull request discussion (e.g. there are extensive comments about analysis in #162), or somewhere else?

All that said, I was able to rough out a (not great) solution.  I created a sub-class of the ZeroOrMore method in xmlchemy.py that performed a recursive search for an element rather than just searching children.  As a demo, I added runs_recursive and text_recursive properties to Paragraph that return the text portion of the hypertext.  

This approach seems less than ideal because paragraphs have several other types of child elements and a recursive search may not be appropriate for some of those, but it seemed like a place to start.  I pushed the changes up to a fork at https://github.com/sanjuroj/python-docx.

Any feedback would be welcome.

**Comment by Yakabuff** [comment]
@scanny is there any chance you can implement any of these solutions

**Comment by roydesbois** [comment]
Until this functionality is implemented in python-docx, this is the workaround I used to redefine the `'text'` property of the `docx.text.paragraph.Paragraph` class such that it includes hyperlinks.

Necessary imports:
```
from docx.text.paragraph import Paragraph
import re
```
First I redefine the `text` property with:
```
Paragraph.text = property(lambda self: GetParagraphText(self))
```

Every time `paragraph.text` is called, the function `GetParagraphText` will be called instead with the instance `paragraph` of type `docx.text.paragraph.Paragraph` as parameter.

The function `GetParagraphText` is implemented as:

```
def GetParagraphText(paragraph)

    def GetTag(element):
        return "%s:%s" % (element.prefix, re.match("{.*}(.*)", element.tag).group(1))

    text = ''
    runCount = 0
    for child in paragraph._p:
        tag = GetTag(child)
        if tag == "w:r":
            text += paragraph.runs[runCount].text
            runCount += 1
        if tag == "w:hyperlink":
            for subChild in child:
                if GetTag(subChild) == "w:r":
                    text += subChild.text
    return text
```

The above implemented is the least intrusive I could find. It requires no modification to the rest of the code, does not need to create new objects, and re-uses when possible the logic already available in python-docx (e.g., paragraph.runs). Hopefully this will help!

**Comment by scanny** [comment]
Nice job @roydesbois :)

**Comment by tomking2** [comment]
Following on from @roydesbois (thanks for the inspiration, a great solution), I needed the requirement to parse down to each individual run so styling and fonts an also be correctly interpreted.

This also uses the built in `qn` to get the full qualified name of the tag, thus not requiring custom regex parsing. What's great about this is that calling `.text` on the paragraph still works as you'd expect, while allowing you to iterate through each run and grab its respective text/styles.

```python
from docx.oxml.shared import qn

def GetParagraphRuns(paragraph):
    def _get(node, parent):
        for child in node:
            if child.tag == qn('w:r'):
                yield Run(child, parent)
            if child.tag == qn('w:hyperlink'):
                yield from _get(child, parent)
    return list(_get(paragraph._element, paragraph))

Paragraph.runs = property(lambda self: GetParagraphRuns(self))
```

**Comment by JStooke** [comment]
@tomking2's solution was great but in my case a lot of the links were embedded. "Click Here" was the text returned rather than the link "Click Here" related to. So I tweaked the approach to pull out the link from document.part.rels and added it to the child.text if it differed from the text (i.e. embedded) so "Click Here" becomes "Click Here"[https://www.google.com]

```python
from docx.text.paragraph import Paragraph
from docx.text.run import Run
from docx.oxml.shared import qn

def GetParagraphRuns(paragraph):
    def _get(node, parent, hyperlinkId=None):
        for child in node:
            if child.tag == qn('w:r'):
                if hyperlinkId:
                    linkToAdd = document.part.rels[hyperlinkId]._target
                    if child.text != linkToAdd:
                        child.text = child.text + f'[{linkToAdd}]'
                yield Run(child, parent)
            if child.tag == qn('w:hyperlink'):
                hlid = child.attrib.get(qn('r:id'))
                yield from _get(child, parent, hlid)
    return list(_get(paragraph._element, paragraph))

Paragraph.runs = property(lambda self: GetParagraphRuns(self))

Paragraph.runs = property(lambda self: GetParagraphRuns(self))
````

**Comment by oliveslongjohns** [comment]
Absolutely love JStooke's solution, but noticed a bug (with a super quick fix). 

`if child.text != linkToAdd:` should be `if linkToAdd not in child.text`, as the hyperlink will never equal the text, and every time the method is called, it adds the hyperlink an additional time. That makes the full solution:

```
from docx.text.paragraph import Paragraph
from docx.text.run import Run
from docx.oxml.shared import qn

def GetParagraphRuns(paragraph):
    def _get(node, parent, hyperlinkId=None):
        for child in node:
            if child.tag == qn('w:r'):
                if hyperlinkId:
                    linkToAdd = document.part.rels[hyperlinkId]._target
                    if linkToAdd not in child.text:
                        child.text = child.text + f'[{linkToAdd}]'
                yield Run(child, parent)
            if child.tag == qn('w:hyperlink'):
                hlid = child.attrib.get(qn('r:id'))
                yield from _get(child, parent, hlid)
    return list(_get(paragraph._element, paragraph))

Paragraph.runs = property(lambda self: GetParagraphRuns(self))

**Comment by JStooke** [comment]
Awesome cheers @oliveslongjohns. I'd forgotten to mention i'd already defined the global variable earlier in my use case. Glad its working for you :D

**Comment by scanny** [comment]
Added in v1.0.0 circa Oct 5, 2023.
