### ISSUE TITLE
stile from other document import doesnt' work

### ISSUE THREAD

**Issue by elyparker** [python-openxml/python-docx#88]
hi  i have this code

from docx import *

source_document = Document('ZONA A.docx')
target_document = Document()

for paragraph in source_document.paragraphs:
    text = paragraph.text
    stile = paragraph.style
    print stile
    target_document.add_paragraph(text,stile)

target_document.save("test.docx")

my original  document is italian winword 

i want create a document similar to orginal but i lost the styles

(name the style are in italian can to be a problem?)

**Comment by abubelinha** [comment]
@scanny If understood correctly, the key for avoiding "[applied styles which do not work](https://github.com/python-openxml/python-docx/issues/88#issuecomment-52575095)" is starting from the correct empty template (also said in many other other issues [#319](https://github.com/python-openxml/python-docx/issues/319#issuecomment-293968148)...). 

Looking to the original question, I think the test tried to recreate an exact copy of the source document starting from a blank document.
Could we just take the original document and empty it to create a blank template? 
i.e. deleting all its contents using your [iter_block_items()](https://github.com/python-openxml/python-docx/issues/40) and [delete_paragraph()](https://github.com/python-openxml/python-docx/issues/33#issuecomment-551891907) functions?


```Python
from docx import *

def emptydoc(doc):
	for el in iter_block_items(doc):
		delete_paragraph(el)
	return(doc)

source_document = Document('ZONA A.docx')
target_document = emptydoc(Document('ZONA A.docx'))
```

Should that work to create a blank template?
I have doubts about looping just `for p in doc.paragraphs` or using `for el in iter_block_items(doc)`, since that would include tables as well.

Do you have any suggestion for an improved `delete_paragraph()` method which is also valid for deleting any element we can find using `iter_block_items()`?
