### ISSUE TITLE
Define paragraph formatting in a table style and a paragraph style

### ISSUE THREAD

**Issue by jf20191031** [python-openxml/python-docx#889]
In the documentation one can read:

> Both a paragraph style and a table style allow paragraph formatting to be specified. These styles provide access to a ParagraphFormat object via their paragraph_format property.
[https://python-docx.readthedocs.io/en/latest/user/styles-using.html#define-paragraph-formatting](url)

I observed a strange behavior but I consider it is rather the default setting and not a bug.

Preliminary remarks: The paragraph formattings in the table style "Table Grid" are based on those of the paragraph style "Normal". 

```python
document = docx.Document()

style2 = document.styles["Normal"]
style2.font.italic = True
style2.paragraph_format.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.JUSTIFY
style2.paragraph_format.space_after = docx.shared.Pt(6)
# Setting up the paragraph style.

my_table = document.add_table(rows=1, cols=4)

my_table.style = "Table Grid"
style = document.styles["Table Grid"]
style.font.italic = True
# It works, but it sets the font type back to upright (non italic)!
style.paragraph_format.space_after = docx.shared.Pt(12)
# It does not work at all, I cannot alter the spacing after the paragraphs here.
style.paragraph_format.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
# It does not work either.
hdr_cells = my_table.rows[0].cells
hdr_cells[0].paragraphs[0].add_run("Name").bold = True 
hdr_cells[1].paragraphs[0].add_run("Postal address").bold = True
hdr_cells[2].paragraphs[0].add_run("Account number").bold = True
hdr_cells[3].paragraphs[0].add_run("Amount").bold = True
# The header is just an example.
row_cells = my_table.add_row().cells
row_cells[0].text = "Name"
row_cells[1].text = "Berlin"
row_cells[2].text = "100000008-0000008"
row_cells[3].text = "1.000.000"
for cell in row_cells:
    cell.paragraphs[0].paragraph_format.space_after = docx.shared.Pt(24)
    cell.paragraphs[0].paragraph_format.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.RIGHT
# It works fine. Inside a cell I can alter the paragraph formatting.
```
It seems to be that you cannot really change the paragraph formatting inside a table style only in a concrete paragraph inside a table cell if the paragraph formatting is also defined in the paragraph style.  The font formattings in the table style and in the paragraph style are mutually dependent.

**Comment by scanny** [comment]
@jf20191031 yeah, I'm not sure what if anything there is unexpected behavior. I'd say in general if you want a customized table style then you should build one from scratch and then assign it, rather than try to modify "built-in" styles too much, but I think to get a firm answer you'd need to inspect the XML that was being produced and work out a way to produce the XML that had the right behaviors using the methods and properties that are present.

I can't quite make out what behavior you're trying to achieve, but that's where I would start, and then look for the best way to achieve that. Word styles are pretty complex, so I would just be looking for a simplest path through that complexity to achieve the goal I had in mind. A good place to start is usually to find the most straightforward way to achieve the result "by hand" using the Word UI and then inspect the XML Word produces so you have an idea what to get `python-docx` to produce.
