### ISSUE TITLE
Definition of docx.enum.style.WD_STYLE_TYPE cannot be auto-completed using PyCharm

### ISSUE THREAD

**Issue by stdedos** [python-openxml/python-docx#890]

**Comment by scanny** [comment]
I expect this is because the members of `WD_STYLE_TYPE` are created by a metaclass at compile time and are not present in static form. This is just the way it's going to be. The members provide a lot of functionality other than just serving as enum members (like generating their own documentation and XML value mappings etc.) Maybe there is some sort of PyCharm configuration file where you can define those for the benefit of your editor.
