### ISSUE TITLE
any plans for a release?

### ISSUE THREAD

**Issue by paweljasinski** [python-openxml/python-docx#899]
I am right now looking at some PRs which looks clean and I need them.
I can fork and individually apply things I need, but ...
Do you plan any release in next 6 months?
What would you include?

**Comment by scanny** [comment]
In general, we are not able to merge PRs we receive without compromising the reliability of the existing code. This is for multiple reasons, but most frequently because they are not accompanied by analysis/design documentation, do not have tests, are not documented, and do not follow the framework of the existing code.

If you want functionality implemented in PRs and you are satisfied with their quality for your purposes, I recommend you merge them into a private fork and get that working well enough for your needs.
