### ISSUE TITLE
customize numbering style

### ISSUE THREAD

**Issue by joannahsu11** [python-openxml/python-docx#938]
I'm trying to use python docx to customize a numbering style when adding a paragraph in a word file.

For example, instead of just adding '1. ' in the beginning of a paragraph, I wanna do 'class #1. '

so I want my paragraph to be like: class #1. xxxx
instead of: 1. xxxx

Is it possible? How to do it?
Any advice would be greatly appreciated. Thanks

**Comment by scanny** [comment]
The short answer is "not easily". There is no API support for this in `python-docx`. This turns out to be a fairly complex problem. If you search Google on `python-docx numbering style` you'll find some odds and ends of folks that have gotten something working to various degrees.

For future reference, please post support questions on Stack Overflow using the `python-docx` tag: https://stackoverflow.com/questions/tagged/python-docx. Support questions generally get more attention over there and are more accessible for folks looking to find things on search. The issues list here is for feature requests and suspected bugs.
