### ISSUE TITLE
Strange table. For Look python-docx table is empty.

### ISSUE THREAD

**Issue by SergeyZaykov** [python-openxml/python-docx#942]
[bad_table.docx](https://github.com/python-openxml/python-docx/files/6439174/bad_table.docx)
Hello!

Table in this document has two rows and one column.

But both MS Word and python-docx  count ony ONE row.
_Debug.Print ActiveDocument.Tables(1).Rows.Count
 1_ 
_>>> len(table.rows)
1_
Python-docx found only one table at the document:
_>>> len(document.tables)
1_

The MS Word thinks that table has ONE row and can print all table's content.
The python-docx  found nothing at table's content.

_Debug.Print ActiveDocument.Tables(1).Rows(1).Cells(1).Range.Text_
**Утверждено на заседании кафедры
«Технология машиностроения»
«7» мая 2018 г., протокол № 10
 Заведующий кафедрой
_________________________ А.А. Маликов**

_from docx import Document
document = Document('bad_table.docx')
table = document.tables[0]
for t in document.tables:
     for row in t.rows:
             for xell in row.cells:
                     print(f"={xell.text}=")_

**==**

**Comment by scanny** [comment]
You can inspect the XML for that table using `print(table._tbl.xml)`.

What I find upon inspection is a table with a single column, a single row, and a single cell.

Inside that cell is a nested table followed by an empty paragraph. That _interior/nested_ table has two rows, each containing a single cell.

So I expect the problem is it visually appears as a table with two rows but your `table` reference is to the outer "container" table which has only one row and no textual content at the level of that cell.
